name: Release

on:
  # Support manually pushing a new release
  workflow_dispatch: {}
  # Trigger when a release or pre-release is published
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Publish to Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          ./gradlew test --info

      - name: Publish
        env:
          MAVEN_SIGNING_KEY: ${{ secrets.MAVEN_SIGNING_KEY }}
          NEXUS_SIGNING_PASSWORD: ${{ secrets.NEXUS_SIGNING_PASSWORD }}
          MAVEN_USER_NAME: ${{ secrets.MAVEN_USER_NAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

        run: |
          echo $MAVEN_SIGNING_KEY | base64 --decode > signing.key

          cat << EOF > gradle.properties
          signingPassword=${NEXUS_SIGNING_PASSWORD}
          sonatypeUsername=${MAVEN_USERNAME}
          sonatypePassword=${MAVEN_PASSWORD}
          EOF

          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -Prelease
